### ISSUE TITLE
Check if speedtest backends are available

### ISSUE THREAD

**Issue by Perflyst** [librespeed/speedtest-android#13]
Currently the app does not check if the backends are working. The web-version does that, would be nice if the android app would do that too.

**Comment by adolfintel** [comment]
The servers are removed from the combobox if the initial ping fails. If you're having trouble with that, give me your server list json file so I can test it.

**Comment by Perflyst** [comment]
The server itself and the backend on / is reachable, though the speedtest files are not available. Web version detects this correctly.

For example
```
[
  {
    "name": "(1) France, Paris (online.net)",
    "server": "//fr1.backend.librespeed.org/",
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php"
  }
]
```

**Comment by adolfintel** [comment]
Ah yes, I see the problem now. The web version downloads empty.php when checking if a server is available, but the android version just sends the request and waits for any kind of response from the server, which is ignored, and a server is considered to be down only if we get no response or fail to connect.
This was done for simplicity, because it's almost as accurate as an actual ping, something that can't be said for the web version.
If you want to change this behavior, you can read the response here instead of simply discarding it: https://github.com/librespeed/speedtest-android/blob/e81c393d22bdb57d44e7e66f9f38f100064cbc9c/Speedtest-Android/app/src/main/java/com/fdossena/speedtest/core/ping/Pinger.java#L30
