### ISSUE TITLE
Feature Request: Add Optional GPS Location

### ISSUE THREAD

**Issue by qazthewsx** [librespeed/speedtest-android#30]
What do you think about adding GPS location as an option when using telemetry on the servers? I think adding GPS location would be possible by using the telemetry_extra advanced parameter (https://github.com/librespeed/speedtest/blob/master/doc.md about half way down the page) to add it to the tests. Could be made so that the option to include GPS as a boolean setting if used when customizing the template. This would be a great help vs. geolocation via IP address. 

Thank you for your work on this project and consideration on this proposed feature.

**Comment by adolfintel** [comment]
Someone has already implemented this feature in a fork of this project. I am personally against it because I think there is no reason to track the user's GPS location just to run a speed test: it gives the potential for abuse, it can cause trouble with GDPR in the EU, and people would start asking why the only speed testing application on F-Droid suddenly has accurate location permission in the manifest. Why do you want this feature?

If you want to implement it, go ahead, it should be fairly easy to do. I don't think I'll merge it though, nothing personal.
